// Single source of truth for plain-English definitions (RM voice). The same
// strings feed the ⓘ tooltips now and the Phase-2 assistant prompt later.
export const GLOSSARY = {
  aqh_share: "Of all the radio listening happening in metro Milwaukee in an average quarter-hour, the slice tuned to us. Higher is better; we're ranked against every station in the market.",
  aqh_persons: "The average number of people listening in any given 15-minute window.",
  cume: "How many different people tuned in at least once during the week — our reach, not our depth.",
  tsl: "Time spent listening — how long the average listener stays with us. Rising TSL means the programming is holding people.",
  tlh: "Total listening hours — every hour of streaming, added up across all listeners. Our total streaming volume.",
  aas: "Average active sessions — how many streams are playing at once, on average. A live read on stream audience.",
  sustainer_mrr: "Monthly recurring revenue from sustaining members — the income we can count on every month. Target $50K.",
  donor_retention: "Of the supporters who gave before this year, the share who gave again. Are we keeping the people we earn?",
  active_donor: "Someone who's given at least once in the last 12 months.",
  reach: "The number of unique people who saw our posts.",
  impressions: "Total times our content was shown — one person can count several times.",
  open_click_rate: "The share of email recipients who opened it, or clicked a link inside.",
  organic_traffic: "Visitors who found us through search or unpaid links, not ads.",
  sustainer_share: "The share of our active donors who give every month as sustaining members. Public radio runs on these.",
  sustainer_conversion: "Of donors who started with a one-time gift, the share who became monthly sustainers.",
  avg_gift: "The typical gift — we show the median, since a few large gifts pull the average up.",
  ltv: "Lifetime giving — every completed gift from a supporter, added up.",
  lapsed_donor: "Someone who gave before but hasn't given in the last 12 months.",
  new_donor: "Someone whose first gift to us landed in this period.",
  payment_method: "How gifts come in — credit card, ACH bank transfer, check, and so on. ACH costs us less and tends to stick.",
  weekly_cume: "How many different people tune in to our broadcast signal at least once in a week — our on-air reach, not how long they stay.",
  aqh_vs_cume: "Cume counts different people reached; AQH is how many are listening in an average quarter-hour. Reach versus intensity.",
  market_rank: "Where our AQH share ranks against every station Nielsen measures in metro Milwaukee.",
  pct_to_budget: "How our revenue so far this year compares to the plan — over 100% is ahead of budget.",
};

export const SECTION_INTRO = {
  program_director: "Who's listening, when, and whether they're staying — across the broadcast signal and the streams.",
  underwriting: "The audience we can offer sponsors — by daypart, device, and demo.",
  digital: "How people find and move through our sites, and the content that brings them in.",
  social: "How each brand's audience is growing and engaging, page by page.",
  finance: "The money: what we've raised against budget, where it comes from, and what's left over.",
  development: "The health of our supporter base: how many give, whether they come back, and what they're worth over time. Org-wide — the brand filter doesn't apply here.",
  board: "How the whole organization is doing — the people we reach, the money against plan, the health of our giving, and where we stand in the market. Org-wide; some cards narrow by brand.",
};

export const DECK = {
  revenue_vs_budget: "Where we stand against the fiscal-year plan, month by month.",
  donor_retention: "We aim to keep 45–50% of last year's donors. Here's how we're tracking.",
  aqh_share_trend: "Our share of Milwaukee's radio listening over the last 14 surveys.",
  sustainer_mrr: "Predictable monthly giving from sustaining members, against the $50K goal.",
  daypart_aas: "When our streams are busiest — average concurrent listeners through the day.",
  hourly_grid: "The week at a glance: where listening peaks by hour and day.",
  tsl_trend: "How long the average streaming listener stays with us, month over month.",
  top_web_content: "The stories pulling people to our sites.",
  top_pages_weekly: "What's drawing traffic right now — the last 7 days. Watch for spikes worth amplifying on social and in the newsletter.",
  top_pages_monthly: "Our durable performers over the last 30 days — the evergreen pages worth investing in. Views show reach; engagement time shows whether people stayed.",
  device_split: "What our streaming audience listens on — useful for ad targeting.",
  retention_cohort: "First-year donors are the leaky bucket; repeat donors stick. Here's the gap.",
  donor_status: "New donors coming in versus our returning base, month by month.",
  sustainer_flow: "Sustaining members gained and lost each month.",
  ltv_tiers: "Where our lifetime giving concentrates — and how few donors hold most of it.",
  payment_mix: "How gifts reach us, by method and dollars.",
  donor_geo: "Where our supporters are.",
  board_reach: "The people we touch across broadcast, streaming, social, and web. Each source is counted separately — we can't de-duplicate a person across them.",
  board_revenue: "Where revenue stands against the fiscal-year plan.",
  board_donors: "The health of our supporter base at a glance.",
  board_market: "Our standing in metro Milwaukee's radio market.",
};
